apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
 - name: mysql-pass
   literals:
      - password=naman
 - name: mysqluser-pass
   literals:
      - myuserpassword=naman
resources:
   - db.yml
   - owncloud.yml